apiVersion: v1
kind: Secret
metadata:
  name: azdevops-secret
type: Opaque
data:
  AZP_URL: <BASE64_ENCODED_ADO_URL>
  AZP_TOKEN: <BASE64_ENCODED_ADO_TOKEN>
  AZP_POOL: <BASE64_ENCODED_ADO_POOL>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: azdevops-build-agent-pool
spec:
  selector:
    matchLabels:
      app: azdevops-build-agent
  template:
    metadata:
      labels:
        app: azdevops-build-agent
    spec:
      containers:
        - name: azdevops-build-agent
          image: raggupta/azdo-rhelubi8-build-docker-agent:v1-latest
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
          env:
            - name: AZP_URL
              valueFrom:
                secretKeyRef:
                  name: azdevops-secret
                  key: AZP_URL
            - name: AZP_TOKEN
              valueFrom:
                secretKeyRef:
                  name: azdevops-secret
                  key: AZP_TOKEN
            - name: AZP_POOL
              valueFrom:
                secretKeyRef:
                  name: azdevops-secret
                  key: AZP_POOL
---

